/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo.est;

public class App {
    public static void main(String[] args) {

        int quantidadeSort = 500;

        for (int i = 1; i <= quantidadeSort ; i++) {
            Sorteio mega = new Sorteio();
            System.out.println("Sorteio numero"+i+"#");
            mega.imprimirSorteio();

        }



    }
}
